[package]
name = "server"
version = "0.1.0"
authors = ["Penn Electric Racing"]
edition = "2018"

[dependencies]
# tokio allows for async io
tokio = { version = "0.3.5", features = ["full"] }
futures-util = "0.3.8"
# Tungstenite is a websocket library
tungstenite = "0.11.1"
tokio-tungstenite = "0.12.0"
# PROST! is a protobuf library
prost = "0.6"
prost-types = "0.6"
# Use env_logger for logging while debugging
log = "0.4"
env_logger = "0.8.2"
# Anyhow makes error handling more ergonomic
anyhow = "1.0.35"
# We use UUIDs for contexts. We need the v4 feature to randomly generate UUIDs
uuid = { version = "0.8", features = ["v4"] }

[build-dependencies]
# Pull in prost-build for codegen
prost-build = "0.6"
