[package]
name = "perdat2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# num = "0.4.0"
byteorder = "1"
snafu = "0.7.0"
tokio-util = { version = "0.7.4", features = ["codec"] }
bytes = "1"