name: Docs

on:
  push:
    branches:
      - master
      - wvauclain/doxygen # testing

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt install doxygen

      - run: bazel build //cpp:docs

      - run: mkdir docs && tar -xf bazel-bin/cpp/docs.tar.gz -C docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
