name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bazel Action
      uses: Penn-Electric-Racing/bazel-action/1.1.0@master
      with:
        args: build //...
