on: push
name: Build and Test Everything
job:
    checks:
        name: run
        runs-on: ubuntu-latest
        steps: 
        - uses: actions/checkout@master
        - name: run
          uses: ngalaiko/bazel-action/1.1.0@master
          with:
              args: test //...
